# Generated by Django 3.1.2 on 2020-10-27 16:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date updated')),
                ('update_week', models.IntegerField(default=44, verbose_name='Week in year')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.action')),
            ],
        ),
    ]
