# Generated by Django 3.1.5 on 2021-01-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='update_week',
            field=models.IntegerField(default=2, verbose_name='Week in year'),
        ),
    ]
