# Generated by Django 3.2.3 on 2021-05-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_auto_20210523_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='count',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='count',
            name='update_week',
            field=models.IntegerField(default=21, verbose_name='Week in year'),
        ),
    ]
